FROM golang:1.12 as builder
RUN mkdir -p /go/src/
WORKDIR /go/
COPY app/ .
RUN go get -d
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -installsuffix cgo -o testrt .

FROM alpine:latest
RUN apk update && apk upgrade && apk add -U tzdata && apk add ca-certificates
ENV TZ=Europe/Moscow
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN mkdir -p /opt/service
WORKDIR /opt/service
COPY --from=builder /go/testrt .

CMD ["/opt/service/testrt"]